apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: second-app #select and expose pod 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
    # - protocol: TCP
    #   port: 80
    #   targetPort: 8080
  type: LoadBalancer